### ISSUE TITLE
Registering the service one should provide absolute path, otherwise exception is thrown

### ISSUE THREAD

**Issue by shahabganji** [hishamco/My.Extensions.Localization.Json#43]
When registering service via `services.AddJsonLocalization`, if the path is not an absolute one it will throw the following exception when resolving the files by `IStringLocalizer`

```cs
// this will cause an error when _localizer["Hello"] is called later on
services.AddJsonLocalization(options => options.ResourcesPath = "Resources");
```

it should be changed to 

```cs
var directory = Path.Combine(Directory.GetCurrentDirectory(), "Resources");
services.AddJsonLocalization(options => options.ResourcesPath = directory);
```
the latter will work perfect.

I think that extra line can be moved to the library itself.

```bash
System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at My.Extensions.Localization.Json.JsonStringLocalizer.<>c__DisplayClass17_0.<BuildResourcesCache>b__0(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at My.Extensions.Localization.Json.JsonStringLocalizer.BuildResourcesCache(String culture)
   at My.Extensions.Localization.Json.JsonStringLocalizer.GetStringSafely(String name)
   at My.Extensions.Localization.Json.JsonStringLocalizer.get_Item(String name)
   at My.Extensions.Localization.Json.Internal.StringLocalizer.get_Item(String name)

HEADERS
=======
Accept-Language: fr-FR
```

**Comment by hishamco** [comment]
Thanks for reporting this, but did you try to run the sample, it should work as expected

**Comment by shahabganji** [comment]
Dear @hishamco, thanks for the prompt reply, yes I ran the [sample](https://github.com/hishamco/My.Extensions.Localization.Json/tree/master/samples/LocalizationSample) with a controller trying to use `IStringLocalizer`

**Comment by hishamco** [comment]
@shahabganji let me try your scenario to make sure that I can reproduce the bug, if you think your fix is a real bug, you could send a PR if you want ..

Thanks

**Comment by shahabganji** [comment]
@hishamco The PR created, hope it helps

**Comment by hishamco** [comment]
I need to check the sample with your changes first before I review the PR

Thanks

**Comment by hishamco** [comment]
@shahabganji I think there's some confusion here you 're using `IStringLocalizer` instead of `IStringlocalizer<T>` which is may causes a strange behavior

Please refer to my new added sample [here](https://github.com/hishamco/My.Extensions.Localization.Json/tree/mvc-sample)

Hope it clarifies what's the preferred localizer you should use as well as resource name conventions

**Comment by hishamco** [comment]
Merged into `dev`

**Comment by shahabganji** [comment]
@hishamco 
I still get the same error, even with `IStringLocalizer<HomeController>`; besides using `IStringLocalizer<T>` only loads messages from `T.{culture}.json` file, right? however, using non-generic `IStringLocalizer` will load messages which are not only for a specific class/controller, like some global shared messages.

I added the following to resolve problem in `Startup -> ConfigureServices`
```cs
services.AddJsonLocalization(
                options => options.ResourcesPath = Path.Combine(
                    Directory.GetCurrentDirectory(), "Resources"));
```

without that it is like : 

<img width="1128" alt="Screen Shot 2020-04-03 at 13 25 59" src="https://user-images.githubusercontent.com/4405518/78342519-aae33e00-75ae-11ea-949f-a14e1fc4d649.png">

note that the response is `500 Internal Server Error`

and this is the log : 
```bash
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HLUNLKCTNMP6", Request id "0HLUNLKCTNMP6:00000001": An unhandled exception was thrown by the application.

System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at My.Extensions.Localization.Json.JsonStringLocalizer.<>c__DisplayClass16_0.<BuildResourcesCache>b__0(String _) in /Users/shahab/dev/playground/My.Extensions.Localization.Json/src/My.Extensions.Localization.Json/JsonStringLocalizer.cs:line 173
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at My.Extensions.Localization.Json.JsonStringLocalizer.BuildResourcesCache(String culture) in /Users/shahab/dev/playground/My.Extensions.Localization.Json/src/My.Extensions.Localization.Json/JsonStringLocalizer.cs:line 162
   at My.Extensions.Localization.Json.JsonStringLocalizer.GetStringSafely(String name) in /Users/shahab/dev/playground/My.Extensions.Localization.Json/src/My.Extensions.Localization.Json/JsonStringLocalizer.cs:line 101
   at My.Extensions.Localization.Json.JsonStringLocalizer.get_Item(String name) in /Users/shahab/dev/playground/My.Extensions.Localization.Json/src/My.Extensions.Localization.Json/JsonStringLocalizer.cs:line 42
   at Microsoft.Extensions.Localization.StringLocalizer`1.get_Item(String name)
   at LocalizationSample.Mvc.Controllers.HomeController.Index() in /Users/shahab/dev/playground/My.Extensions.Localization.Json/samples/LocalizationSample.Mvc/Controllers/HomeController.cs:line 19
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by hishamco** [comment]
That means the error occurs when you are using `IStringLocalizer` alone or beside `IStringLocalizer<T>` right?

**Comment by shahabganji** [comment]
I just checked out the project and run the new sample as dotnet project. I have the same error no matter which type of usage,  `IStringLocalizer<T>` alone also produces the error. using both together also produces error.

my current controller :

```cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace LocalizationSample.Mvc.Controllers
{
    [Route("")]
    public class HomeController : Controller
    {
        private readonly IStringLocalizer<HomeController> _localizer;

        public HomeController(IStringLocalizer<HomeController> localizer)
        {
            _localizer = localizer ?? throw new ArgumentNullException(nameof(localizer));
        }

        public string Index()
        {
            var result = _localizer["Hello"].Value;
            
            return result;
        }
    }
}
```
and `Startup.cs`

```cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace LocalizationSample.Mvc
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddJsonLocalization(options => options.ResourcesPath = "Resources");
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRequestLocalization("en-US", "fr-FR");

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints => endpoints.MapControllers());
        }
    }
}
```

I have two resource files, `HomeController.fr-FR.json` and `fr-FR.json`

changed the line to `services.AddJsonLocalization( options => options.ResourcesPath = Path.Combine(Directory.GetCurrentDirectory(), "Resources"));` and it works like a charm.

**Comment by shahabganji** [comment]
Also changing [Line 174](https://github.com/hishamco/My.Extensions.Localization.Json/blob/master/src/My.Extensions.Localization.Json/JsonStringLocalizer.cs#L174) to 

```cs
.SetBasePath(Path.Combine(Directory.GetCurrentDirectory() ,_resourcesPath))
``` 
solved the issue.

**Comment by hishamco** [comment]
I did few updates after I support `JsonHtmlLocalizer`, I will try to use `IStringLocalizer` alongside with `IStringLocalizer` to reproduce the error

**Comment by shahabganji** [comment]
you mean `IStringLocalizer` alongside with `IStringLocalizer<T>`? but in this case `IStringLocalizer<T>` also throws an exception. Anyway thanks for the follow ups.

**Comment by hishamco** [comment]
Seems I confused, could please try the latest sample `LocalizationSample.Mvc` and let me know what are the required changes to raise the error

**Comment by shahabganji** [comment]
I exactly **did** that. please check [here](https://github.com/hishamco/My.Extensions.Localization.Json/issues/43#issuecomment-608323488) and [here](https://github.com/hishamco/My.Extensions.Localization.Json/issues/43#issuecomment-608319226)

> I just checked out the project and run the new sample as dotnet project. I have the same error no matter which type of usage, IStringLocalizer<T> alone also produces the error. using both together also produces error.

**Comment by hishamco** [comment]
Seems you didn't fetch the latest bits ;) I just merged a new commits anyhow I don't have such `T.{culture}.json` file, furthermore there's no error occurs on `IStringLocalizer<HomeController>` at all

**Comment by hishamco** [comment]
This is a French version of how Privacy page is look like at my end

![Privacy](https://user-images.githubusercontent.com/3237266/78345422-4e7c2080-75a6-11ea-81ef-c61038d24397.jpg)

**Comment by shahabganji** [comment]
By `T` I meant `HomeController`, I pulled the latest version, however, the problem still exist.

* URL: `https://localhost:8001/Home/Privacy/?culture-fr-FR&ui-culture=fr-FR`
* error the same as before: 
```bash
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HLUNMASR1PM7", Request id "0HLUNMASR1PM7:00000001": An unhandled exception was thrown by the application.

System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at My.Extensions.Localization.Json.JsonStringLocalizer.<>c__DisplayClass16_0.<BuildResourcesCache>b__0(String _) in /Users/shahab/dev/playground/My.Extensions.Localization.Json/src/My.Extensions.Localization.Json/JsonStringLocalizer.cs:line 173
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at My.Extensions.Localization.Json.JsonStringLocalizer.BuildResourcesCache(String culture) in /Users/shahab/dev/playground/My.Extensions.Localization.Json/src/My.Extensions.Localization.Json/JsonStringLocalizer.cs:line 162
   at My.Extensions.Localization.Json.JsonStringLocalizer.GetStringSafely(String name) in /Users/shahab/dev/playground/My.Extensions.Localization.Json/src/My.Extensions.Localization.Json/JsonStringLocalizer.cs:line 101
   at My.Extensions.Localization.Json.JsonStringLocalizer.get_Item(String name) in /Users/shahab/dev/playground/My.Extensions.Localization.Json/src/My.Extensions.Localization.Json/JsonStringLocalizer.cs:line 42
   at Microsoft.Extensions.Localization.StringLocalizer`1.get_Item(String name)
   at LocalizationSample.Mvc.Controllers.HomeController.Privacy() in /Users/shahab/dev/playground/My.Extensions.Localization.Json/samples/LocalizationSample.Mvc/Controllers/HomeController.cs:line 22
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I did the same thing to solve the problem and it worked. 
I don't know whether the OS matters or not, mine is Mac OS X

**Comment by hishamco** [comment]
I see, I don't now you are running on Mac OS, so I need to create a functional test, so AzurePipeline should fail if there's issue

I will try create it ASAP

Thanks again

**Comment by hishamco** [comment]
Also I will try your change to check if it's work with me too on Windows

**Comment by hishamco** [comment]
If you wish to create a functional test that runs the `LocalizationSample.Mvc` that I created in you PR it will be very good to make sure that your changes works on ever OS

**Comment by shahabganji** [comment]
No problem  I'll put a time on that.

**Comment by hishamco** [comment]
I request few changes on your PR, please fix them and let me know if you need help on creating a functional test

**Comment by shahabganji** [comment]
Sure, just give me some time till evening, currently at the middle of some important stuff, is that okay?

**Comment by hishamco** [comment]
Take your time .. I will try to fix and improve something else meanwhile

**Comment by shahabganji** [comment]
Dear @hishamco, check PR #44 . I've added a functional test for one of the samples, `LocalizationSample`, do we need another one for `LocalizationSample.Mvc`?

**Comment by hishamco** [comment]
I will have a look ...

Thanks

**Comment by shahabganji** [comment]
@hishamco Please also update the nuget feed. thanks 🙏

**Comment by hishamco** [comment]
Do you mean upload a NuGet package?

**Comment by shahabganji** [comment]
Yes.

**Comment by hishamco** [comment]
I need to add some new features, then I will release `2.1.0` hope this will not take more than few days
